---
- name: Create the common config directory
  file: path=/etc/common/config mode=0755 owner=droplet-user group=droplet-user state=directory recurse=yes

- name: Create the directory to hold the API key
  file: path=/etc/do mode=0755 owner=droplet-user group=droplet-user state=directory recurse=yes

- name: Template the API key variable file
  template: src=api_token.yml.j2 dest=/etc/do/api_token.yml mode=0755 owner=droplet-user group=droplet-user
